version: "3.11"

services:
    osrm:
        container_name: osrm
        build: ./Osrm
        ports:
            - "8000:5000"
    rabbit:
        image: rabbitmq:3-management
        container_name: rabbit
        ports:
        - "5672:5672"
        - "15672:15672"
        volumes:
            - ./rabbitmq/data/:/var/lib/rabbitmq/
            - ./rabbitmq/log/:/var/log/rabbitmq
        networks:
            - rabbitmq_go_net
    database: 
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_PASSWORD: passwd
            POSTGRES_USER: admin
        ports:
            - 5432:5432
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    seq:
        container_name: seq
        image: datalust/seq:latest
        environment:
            ACCEPT_EULA: Y
        ports:
            - 5341:80


networks:
    rabbitmq_go_net:
        driver: bridge

    # planner:
    #     build: ./Planner/Planner
    
