// <auto-generated />
using System;
using CargoApp.Modules.Cargoes.Infrastructure.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CargoApp.Modules.Cargoes.Infrastructure.DAL.Migrations
{
    [DbContext(typeof(CargoDbContext))]
    [Migration("20231018205352_UpdateLocationCompanyDriverAndCargoEntities")]
    partial class UpdateLocationCompanyDriverAndCargoEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cargoes")
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CargoApp.Modules.Cargoes.Core.CargoAggregate.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocationFromId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocationToId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("_deliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("_driverId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("_expectedDeliveryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("_receiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("_senderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocationFromId");

                    b.HasIndex("LocationToId");

                    b.HasIndex("_driverId");

                    b.HasIndex("_receiverId");

                    b.HasIndex("_senderId");

                    b.ToTable("Cargoes", "cargoes");
                });

            modelBuilder.Entity("CargoApp.Modules.Cargoes.Core.CompanyAggregate.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("_companyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CompanyName");

                    b.HasKey("Id");

                    b.ToTable("Companies", "cargoes");
                });

            modelBuilder.Entity("CargoApp.Modules.Cargoes.Core.DriverAggregate.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HomeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("_isActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("HomeId");

                    b.ToTable("Drivers", "cargoes");
                });

            modelBuilder.Entity("CargoApp.Modules.Cargoes.Core.LocationAggregate.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lon")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OsmId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Locations", "cargoes");
                });

            modelBuilder.Entity("CargoApp.Modules.Cargoes.Core.CargoAggregate.Cargo", b =>
                {
                    b.HasOne("CargoApp.Modules.Cargoes.Core.LocationAggregate.Location", "_from")
                        .WithMany()
                        .HasForeignKey("LocationFromId");

                    b.HasOne("CargoApp.Modules.Cargoes.Core.LocationAggregate.Location", "_to")
                        .WithMany()
                        .HasForeignKey("LocationToId");

                    b.HasOne("CargoApp.Modules.Cargoes.Core.DriverAggregate.Driver", "_driver")
                        .WithMany()
                        .HasForeignKey("_driverId");

                    b.HasOne("CargoApp.Modules.Cargoes.Core.CompanyAggregate.Company", "_receiver")
                        .WithMany()
                        .HasForeignKey("_receiverId");

                    b.HasOne("CargoApp.Modules.Cargoes.Core.CompanyAggregate.Company", "_sender")
                        .WithMany()
                        .HasForeignKey("_senderId");

                    b.Navigation("_driver");

                    b.Navigation("_from");

                    b.Navigation("_receiver");

                    b.Navigation("_sender");

                    b.Navigation("_to");
                });

            modelBuilder.Entity("CargoApp.Modules.Cargoes.Core.DriverAggregate.Driver", b =>
                {
                    b.HasOne("CargoApp.Modules.Cargoes.Core.CompanyAggregate.Company", null)
                        .WithMany("_drivers")
                        .HasForeignKey("CompanyId");

                    b.HasOne("CargoApp.Modules.Cargoes.Core.LocationAggregate.Location", "_home")
                        .WithMany()
                        .HasForeignKey("HomeId");

                    b.Navigation("_home");
                });

            modelBuilder.Entity("CargoApp.Modules.Cargoes.Core.CompanyAggregate.Company", b =>
                {
                    b.Navigation("_drivers");
                });
#pragma warning restore 612, 618
        }
    }
}
